apiVersion: v1
kind: Pod
metadata:
  name: service01-tf-plan-7
spec:
  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {} 
  
  initContainers:
  - name: tf-init
    image: adhocam/azurerm:7
    command:
    - sh
    - "-c"
    - |
      cd /terraform/service01
      terraform init --reconfigure
      cp -r /terraform /iac
      ls /iac/terraform -al
    volumeMounts:
    - mountPath: /iac
      name: shared-data

  containers:
  - name: tf-plan
    image: adhocam/azurerm:7
    command:
    - sh
    - "-c"
    - |
      cd iac/terraform/service01
      terraform plan
    envFrom:
    - secretRef:
        name: azcreds
    volumeMounts:
    - mountPath: /iac
      name: shared-data