apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-plan
  labels:
    app: iac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iac
  template:
    metadata:
      labels:
        app: iac
    spec:
      volumes:
      - name: shared-data
        emptyDir: {} 
      
      initContainers:
      - name: tf-init
        image: adhocam/azurerm:4
        command:
        - sh
        - "-c"
        - |
          cd /terraform/service01
          terraform init
          cp -r /terraform /iac
          ls /iac/terraform -al
        volumeMounts:
        - mountPath: /iac
          name: shared-data

      containers:
      - name: tf-plan
        image: adhocam/azurerm:4
        command:
        - sh
        - "-c"
        - |
          cd iac/terraform/service01
          terraform plan
        envFrom:
        - secretRef:
            name: azcreds
        volumeMounts:
        - mountPath: /iac
          name: shared-data