apiVersion: v1
kind: Pod
metadata:
  name: service01-tf-apply-10
spec:
  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {} 
  
  initContainers:
  - name: tf-init
    image: adhocam/azurerm:10
    command:
    - sh
    - "-c"
    - |
      cd /terraform/service01
      terraform init
      cp -r /terraform /iac
      ls /iac/terraform -al
    envFrom:
    - secretRef:
        name: azcreds
    volumeMounts:
    - mountPath: /iac
      name: shared-data

  containers:
  - name: tf-apply
    image: adhocam/azurerm:10
    command:
    - sh
    - "-c"
    - |
      cd iac/terraform/service01
      terraform apply -auto-approve
    envFrom:
    - secretRef:
        name: azcreds
    volumeMounts:
    - mountPath: /iac
      name: shared-data 